language: python
python:
    - "3.4"
    - "3.5"
# how to install dependencies:
install: "pip install -r requirements.txt"
# how to run tests
# lol there aren't any (and this is NOT OK)

notifications:
    email:
        on_success: change

sudo: false
