language: python
python:
- '3.4'
- '3.5'
install: pip install -r requirements.txt
script: nosetests
notifications:
  email:
    on_success: change
sudo: false
deploy:
  skip_cleanup: true
  provider: script
  script: tools/dropbox-deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_0c2ef6cbca64_key -iv $encrypted_0c2ef6cbca64_iv
  -in auth.yaml.enc -out auth.yaml -d
